kind: Deployment
apiVersion: apps/v1
metadata:
  name: player
  namespace: baseball
  labels:
    app: player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player
  template:
    metadata:
      labels:
        app: player
    spec:
      containers:
        - name: player
          image: nschultz/fantasy-baseball-player:{{version}}
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: PLAYER_DATABASE
              valueFrom:
                secretKeyRef:
                  name: player-postgres-secret
                  key: dbname
            - name: PLAYER_DATABASE_HOST
              value: "player-database"
            - name: PLAYER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: player-postgres-secret
                  key: password
            - name: PLAYER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: player-postgres-secret
                  key: username
            - name: POSITION_SERVICE_HOST
              value: "position:8080"
            - name: POSITION_SERVICE_VERSION
              value: "v1"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
